require "user.plugins"
require "user.options"
require "user.keybindings"
require "user.theme"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.nvim-tree"
require "user.bufferline"
require 'user.statusline'
require "user.trouble"
require "user.whichkey"
require "user.dashboard"
require "user.lang.golang"
require "user.neogit"
require "user.copilot"
-- require "user.tabout"

